[package]
name = "csv-query"
version = "1.0.0"
edition = "2021"
authors = ["Adeleke Oluwatobi <tobiadiks@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
